export const nav_content = {
    brand: "Equips",
    merge_pdf: "Merge PDF",
    split_pdf: "Split PDF",
    compress_pdf: "Compress PDF",
    convert_pdf: "Convert PDF",
    convert_to_pdf: "Convert to PDF",
    jpg_to_pdf: "JPG to PDF",
    word_to_pdf: "WORD to PDF",
    powerpoint_to_pdf: "POWERPOINT to PDF",
    excel_to_pdf: "EXCEL to PDF",
    html_to_pdf: "HTML to PDF",
    web_to_pdf: "Web to PDF",
    markdown_to_pdf: "Markdown to PDF",
    convert_from_pdf: "Convert from PDF",
    read_edit_pdf: "Read & Edit PDF",
    pdf_to_jpg: "PDF to JPG",
    pdf_to_word: "PDF to WORD",
    pdf_to_powerpoint: "PDF to POWERPOINT",
    pdf_to_excel: "PDF to EXCEL",
    pdf_to_pdf_a: "PDF to PDF/A",
    pdf_to_text: "PDF to text",
    pdf_to_html: "PDF to HTML",
    pdf_to_markdown: "PDF to Markdown",
};