export const nav_content = {
  brand: "Equips",
  merge_pdf: "Combinar PDF",
  split_pdf: "Dividir PDF",
  compress_pdf: "Comprimir PDF",
  convert_pdf: "Convertir PDF",
  convert_to_pdf: "Convertir a PDF",
  jpg_to_pdf: "JPG a PDF",
  word_to_pdf: "Word a PDF",
  powerpoint_to_pdf: "Powerpoint a PDF",
  web_to_pdf: "Web a PDF",
  markdown_to_pdf: "Markdown a PDF",
  excel_to_pdf: "Excel a PDF",
  html_to_pdf: "HTML a PDF",
  convert_from_pdf: "Convertir desde PDF",
  read_edit_pdf: "Leer y editar PDF",
  pdf_to_jpg: "PDF a JPG",
  pdf_to_word: "PDF a Word",
  pdf_to_powerpoint: "PDF a Powerpoint",
  pdf_to_excel: "PDF a Excel",
  pdf_to_pdf_a: "PDF a PDF/A",
  pdf_to_text: "PDF a texto",
  pdf_to_html: "PDF a HTML",
  pdf_to_markdown: "PDF a Markdown",
};
